export const COUNTRIES = [
  { code: 'BE', name: 'Belgien', flag: '🇧🇪' },
  { code: 'BG', name: 'Bulgarien', flag: '🇧🇬' },
  { code: 'DK', name: 'Dänemark', flag: '🇩🇰' },
  { code: 'DE', name: 'Deutschland', flag: '🇩🇪' },
  { code: 'EE', name: 'Estland', flag: '🇪🇪' },
  { code: 'FI', name: 'Finnland', flag: '🇫🇮' },
  { code: 'FR', name: 'Frankreich', flag: '🇫🇷' },
  { code: 'GR', name: 'Griechenland', flag: '🇬🇷' },
  { code: 'IE', name: 'Irland', flag: '🇮🇪' },
  { code: 'IS', name: 'Island', flag: '🇮🇸' },
  { code: 'IT', name: 'Italien', flag: '🇮🇹' },
  { code: 'HR', name: 'Kroatien', flag: '🇭🇷' },
  { code: 'LV', name: 'Lettland', flag: '🇱🇻' },
  { code: 'LT', name: 'Litauen', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxemburg', flag: '🇱🇺' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'NL', name: 'Niederlande', flag: '🇳🇱' },
  { code: 'NO', name: 'Norwegen', flag: '🇳🇴' },
  { code: 'AT', name: 'Österreich', flag: '🇦🇹' },
  { code: 'PL', name: 'Polen', flag: '🇵🇱' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'RO', name: 'Rumänien', flag: '🇷🇴' },
  { code: 'SE', name: 'Schweden', flag: '🇸🇪' },
  { code: 'CH', name: 'Schweiz', flag: '🇨🇭' },
  { code: 'SK', name: 'Slowakei', flag: '🇸🇰' },
  { code: 'SI', name: 'Slowenien', flag: '🇸🇮' },
  { code: 'ES', name: 'Spanien', flag: '🇪🇸' },
  { code: 'CZ', name: 'Tschechien', flag: '🇨🇿' },
  { code: 'TR', name: 'Türkei', flag: '🇹🇷' },
  { code: 'HU', name: 'Ungarn', flag: '🇭🇺' },
  { code: 'GB', name: 'Vereinigtes Königreich', flag: '🇬🇧' },
  { code: 'CY', name: 'Zypern', flag: '🇨🇾' },
];

export const FIELDS = [
  'Elektrotechnik',
  'Gastronomie',
  'Gesundheit',
  'Informatik',
  'Kaufmännisch',
  'Mechatronik',
  'Mediengestaltung',
  'Metalltechnik',
  'Wirtschaft',
];

export const LANGUAGES = [
  'Dänisch',
  'Deutsch',
  'Englisch',
  'Finnisch',
  'Französisch',
  'Griechisch',
  'Italienisch',
  'Kroatisch',
  'Niederländisch',
  'Norwegisch',
  'Polnisch',
  'Portugiesisch',
  'Rumänisch',
  'Schwedisch',
  'Slowakisch',
  'Spanisch',
  'Tschechisch',
  'Türkisch',
  'Ungarisch',
];

export function getCountryByName(name) {
  return COUNTRIES.find((c) => c.name === name);
}
